// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3y6oDNshzKjwE-jQL9MiPY6895HLJ9Gw',
    appId: '1:492540809193:web:8548c2a60a4309e270c578',
    messagingSenderId: '492540809193',
    projectId: 'wamo-26a85',
    authDomain: 'wamo-26a85.firebaseapp.com',
    storageBucket: 'wamo-26a85.firebasestorage.app',
    measurementId: 'G-RXPP8L3XYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyfRf2_d0PUMSgrkF7rCEs1cRWgbzKRRo',
    appId: '1:492540809193:android:6c12dfb64efd50bc70c578',
    messagingSenderId: '492540809193',
    projectId: 'wamo-26a85',
    storageBucket: 'wamo-26a85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6L3_hXSn-4oA5_1w0eWNxoialY3HSROY',
    appId: '1:492540809193:ios:786aa50c5ed864ef70c578',
    messagingSenderId: '492540809193',
    projectId: 'wamo-26a85',
    storageBucket: 'wamo-26a85.firebasestorage.app',
    iosBundleId: 'com.banditor.wamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6L3_hXSn-4oA5_1w0eWNxoialY3HSROY',
    appId: '1:492540809193:ios:786aa50c5ed864ef70c578',
    messagingSenderId: '492540809193',
    projectId: 'wamo-26a85',
    storageBucket: 'wamo-26a85.firebasestorage.app',
    iosBundleId: 'com.banditor.wamo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3y6oDNshzKjwE-jQL9MiPY6895HLJ9Gw',
    appId: '1:492540809193:web:a7f1ce6b8bb440b770c578',
    messagingSenderId: '492540809193',
    projectId: 'wamo-26a85',
    authDomain: 'wamo-26a85.firebaseapp.com',
    storageBucket: 'wamo-26a85.firebasestorage.app',
    measurementId: 'G-VNH5S6ZDK4',
  );
}
